apiVersion: app.aispec.org/v1alpha1
kind: AIApp
metadata:
  name: exchangerates
spec:
  assistants:
    - model: meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo
      type: text
      # Tests for this assistant
      tests:
      - name: check usd to gbp rate
        steps:
          - prompt: what is the usd to gbp exchange rate?
            expected_output: the usd to gbp exchange rate
      - name: usdgbp
        steps:
          - prompt: usdgbp
            expected_output: the usd to gbp exchange rate only. it should specifically mention both usd and gbp and not other currencies. if it mentions other currencies, FAIL the test
      apis:
        - name: Exchange Rates API
          description: Get latest currency exchange rates
          url: https://open.er-api.com/v6
          schema: |-
            openapi: 3.0.0
            info:
              title: Exchange Rates API
              description: Get latest currency exchange rates
              version: "1.0.0"
            servers:
              - url: https://open.er-api.com/v6
            paths:
              /latest/{currency}:
                get:
                  operationId: getExchangeRates
                  summary: Get latest exchange rates
                  description: Get current exchange rates for a base currency
                  parameters:
                    - name: currency
                      in: path
                      required: true
                      description: Base currency code (e.g., USD, EUR, GBP)
                      schema:
                        type: string
                  responses:
                    '200':
                      description: Successful response with exchange rates
                      content:
                        application/json:
                          schema:
                            type: object
                            properties:
                              result:
                                type: string
                                example: "success"
                              provider:
                                type: string
                                example: "Open Exchange Rates"
                              base_code:
                                type: string
                                example: "USD"
                              time_last_update_utc:
                                type: string
                                example: "2024-01-19 00:00:01"
                              rates:
                                type: object
                                properties:
                                  EUR:
                                    type: number
                                    example: 0.91815
                                  GBP:
                                    type: number
                                    example: 0.78543
                                  JPY:
                                    type: number
                                    example: 148.192
                                  AUD:
                                    type: number
                                    example: 1.51234
                                  CAD:
                                    type: number
                                    example: 1.34521
